version: '3.1'
services:
  app:
    container_name: spring_sorokow
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - sqlite3
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
